name: Build/release

on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build macOS app
        if: runner.os == 'macOS'
        run: yarn build-mac

      - name: Build Windows app
        if: runner.os == 'Windows'
        run: yarn build-win

      - name: Build Linux app
        if: runner.os == 'Linux'
        run: yarn build-linux

      - name: Release artifacts
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
