name: Build/release

on: 
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Electron app (per OS)
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            yarn build-mac
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            yarn build-win
          else
            yarn build-linux
          fi

      - name: Release artifacts
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
